matrix:
  include:
    - os: osx
      language: node_js
      node_js:
        - 12

    - os: linux
      language: node_js
      node_js:
        - 12
      addons:
        apt:
          packages:
            - libgconf-2-4

    - os: windows
      language: node_js
      node_js:
        - 12

cache:
  npm: true
  directories:
    - ~/.cache

install:
  - npm ci

script:
  - npm run ci
  - npm run build

notifications:
  email:
    on_success: never
    on_failure: change
