os: linux

language: node_js

node_js:
  - 12

addons:
  apt:
    packages:
      - libgconf-2-4

cache:
  npm: true
  directories:
    - ~/.cache

stages:
  - tests
  - build

install:
  - npm ci

jobs:
  include:
    - stage: Tests
      name: E2E Test
      script:
        - npm run ci

    - stage: Build
      name: Build
      script:
        - npm run build

deploy:
  provider: pages
  local_dir: './storybook-public'
  github_token: $GITHUB_TOKEN
  on:
    condition: os = linux AND tag IS present

notifications:
  email:
    on_success: never
    on_failure: change
