os: linux

language: node_js

node_js:
  - 12

addons:
  apt:
    packages:
      - libgconf-2-4

cache:
  npm: true
  directories:
    - ~/.cache

stages:
  - tests
  - build
  - deploy

install:
  - npm ci

jobs:
  include:
    - stage: tests
      name: E2E Test
      script:
        - npm run ci

    - stage: build
      name: Build
      script:
        - npm run build

    - stage: deploy
      name: Deploy
      script: skip
      deploy:
        - provider: pages
          local_dir: './storybook-public'
          github_token: $GITHUB_TOKEN
          on:
            - tags: true

notifications:
  email:
    on_success: never
    on_failure: change
