matrix:
  include:
    - os: osx
      language: node_js
      node_js:
        - node

    - os: linux
      language: node_js
      node_js:
        - node
      addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-multilib
          - g++-8
          - g++-multilib
          - icnsutils
          - graphicsmagick
          - xz-utils
          - xorriso
          - rpm

    - os: windows
      language: node_js
      node_js:
        - node

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - npm run ci
  - npm run build

notifications:
  email:
    on_success: never
    on_failure: change
