matrix:
  include:
    - os: osx
      language: node_js
      node_js:
        - node

    - os: linux
      language: node_js
      node_js:
        - node
      addons:
      apt:
        packages:
          - xvfb
          - libgtk-3-dev
          - libnotify-dev
          - libgconf-2-4
          - libnss3
          - libxss1
          - libasound2

    - os: windows
      language: node_js
      node_js:
        - node

cache:
  directories:
    - node_modules

install:
  - npm install
  - npx cypress install

script:
  - npm run ci
  - npm run build

notifications:
  email:
    on_success: never
    on_failure: change
